data_dir: "auto"

datamodule_params:
  batch_size: 32
  num_workers: 8
  pin_memory: true

hparams:
  train_val_ratio: 0.8
  train_id_targets:
    - 1
    - 3
    - 5
    - 7
  train_ood_targets:
    - 0
    - 2
    - 4
  test_ood_targets:
    - 6
    - 8
    - 9